### ISSUE TITLE
Centralize project contributor and author recognitions

### ISSUE THREAD

**Issue by oxcabe** [SIMDE-ULL/SIMDE#104]
## Description 

Author recognition is spread throughout the entire project. Some examples are:

https://github.com/SIMDE-ULL/SIMDE/blob/e3fa8e662920c5fdbd54e4f0534c9d2da0268262/docs/en/autor.md?plain=1#L1-L19

and

https://github.com/SIMDE-ULL/SIMDE/blob/e3fa8e662920c5fdbd54e4f0534c9d2da0268262/src/interface/components/Superescalar/modal/AutorModalComponent.tsx#L22-L43

## Proposed solution

* Use a general recognition name (e.g. __"The SIMDE authors"__) for smaller inputs, such as the `"author"` field in `package.json`.
* Add a general __"Contributors"__ section in the `README.md`, managed and maintained through [Recognize All Contributors](https://allcontributors.org/).
* Add an __"About"__ section in the front-end, listing front-end contributors.
* Add an __"Acknowledgements"__ section in the documentation, listing documentation contributors.
* Add the list of contributors to each release message and `CHANGELOG` section.
* Finally, update them accordingly when new releases are created.

**Comment by endes0** [comment]
I suggest also to add a **"Citation"** section like [Ripes](https://github.com/mortbopet/Ripes#building) as the root of this project is academic.

**Comment by oxcabe** [comment]
Sounds good to me.

**Comment by endes0** [comment]
@all-contributors please add @icasrod for creating the original simulator + BDFL.
@all-contributors please add @adrianabreu  for creating the web version.
@all-contributors please add @alu0100884012 for Melissa: implementing the VLIW machine.
@all-contributors please add @oxcabe for maintaining the project.
@all-contributors please add @endes0 for maintaining the project.

**Comment by endes0** [comment]
https://github.com/all-contributors please add @icasrod for creating the original simulator + BDFL. please add @adrianabreu for creating the web version. please add @alu0100884012 for Melissa: implementing the VLIW machine. please add @oxcabe for maintaining the project. please add @endes0 for maintaining the project.

**Comment by oxcabe** [comment]
@all-contributors
please add @icasrod for creating the original simulator + BDFL.
please add @adrianabreu for creating the web version.
please add @alu0100884012 for Melissa: implementing the VLIW machine.
please add @oxcabe for maintaining the project. please add @endes0 for maintaining the project.

**Comment by endes0** [comment]
@all-contributors
please add @icasrod for 🔬📆🧑‍🏫🤔💡📖.
please add @adrianabreu for 📦🎨.
please add @alu0100884012 aka Melissa for 📦 .
please add @oxcabe for 🧑‍🏫🚧🚇. 
please add @endes0 for ⚠️🚧.

**Comment by endes0** [comment]
@all-contributors
please add @icasrod for research, projectManagement, mentoring, ideas, example, doc.
please add @adrianabreu for platform, design.
please add @alu0100884012 for platform.
please add @oxcabe for mentoring, maintenance, platform.
please add @endes0 for test, maintenance.

Sorry to all people mentioned for the spam, the bot is giving us a fight!

**Comment by endes0** [comment]
I give up

**Comment by oxcabe** [comment]
Is it refreshing after each new comment?

**Comment by oxcabe** [comment]
@all-contributors
please add @alu0100884012 for platform.
please add @oxcabe for mentoring, maintenance, platform.
please add @endes0 for test, maintenance.

**Comment by oxcabe** [comment]
@all-contributors please add @endes0 for test, maintenance.
