### ISSUE TITLE
Problemas con los registros

### ISSUE THREAD

**Issue by nicolasjml99** [SIMDE-ULL/SIMDE#160]
Buenos días, probando la máquina SIMDE nos hemos encontrado con un posible error. Y es que la maquina tiene como tal 64 registros (de 0 a 63) que es lo que se puede ver en los registros. Nos hemos encontrado que si usas el registro F64 por ejemplo nos deja utilizarlo y el resultado da correcto. Pero por ejemplo si deseamos utilizar el registro F65 en adelante salta error y no deja ni cargar el código.
Un saludo, que tengáis buen día.

**Comment by oxcabe** [comment]
Hoy le echo un ojo y lo arreglamos, gracias por reportarlo!

**Comment by endes0** [comment]
https://github.com/SIMDE-ULL/SIMDE/blob/754d0bfcffea02f6da2dca91756caee8b1153c81/src/core/Common/CodeParser.ts#L239C34-L239C35

La culpa son de estas y subsiguientes comparaciones, tendrían que ser `>=`. Hago PR esta tarde.
