### ISSUE TITLE
Problemas con la instrucción SUB de la máquina VLIW

### ISSUE THREAD

**Issue by nicolasjml99** [SIMDE-ULL/SIMDE#163]
Buenos días, nos hemos encontrado un grave problema en nuestra ejecución de VLIW y es que el programa no traga la operación SUB, en el momento de esa instrucción la máquina se queda colgada y no sigue. En cambio si cambiamos el sub por otra operación si que funciona a la perfección.
Un saludo

**Comment by oxcabe** [comment]
Buenos días, gracias por reportarlo.

Me podrías pasar por aquí un ejemplo reproducible? Creo que sólamente necesitaría los dos ficheros de código VLIW. Puedes subir los ficheros en el comentario o escribirlos directamente en un bloque de código.

**Comment by nicolasjml99** [comment]
Sin problemas, te adjunto una ejecución con SUB implementado y una posible planificación
[FinalCode.txt](https://github.com/SIMDE-ULL/SIMDE/files/15220042/FinalCode.txt)
[PlanFin11.txt](https://github.com/SIMDE-ULL/SIMDE/files/15220044/PlanFin11.txt)

**Comment by oxcabe** [comment]
Genial, gracias! Si esto que me has pasado es parte de tus prácticas considera eliminar ahora los ficheros de tu comentario. En el caso de que todos tus compañeros tengan la misma práctica, podrían plagiar tu trabajo. Yo ya la tengo descargada para reproducir el bug :+1:.

De nuevo, gracias, un saludo y mucho ánimo con las prácticas!

**Comment by nicolasjml99** [comment]
Perfecto, muchísimas gracias. Que tengas buen día

**Comment by endes0** [comment]
Solucionado, posiblemente mañana  ya este en producción el arreglo. 
Btw, este problema se da con todas las instrucciones ALU enteras a excepción de ADD, ADDI y MULT.
